<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UG1IGJU" name="testNGDemonstration.TestNGTestClass" tests="7" failures="0" timestamp="27 Mar 2017 07:21:36 GMT" time="0.029" errors="1">
  <testcase name="test2" time="0.002" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.004" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.002" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test1" time="0.003" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test3" time="0.003" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.002" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test4" time="0.013" classname="testNGDemonstration.TestNGTestClass">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.test4() didn&#039;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.test4() didn't finish within the time-out 1
	at java.lang.Thread.interrupt0(Native Method)
	at java.lang.Thread.interrupt(Unknown Source)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test4 -->
</testsuite> <!-- testNGDemonstration.TestNGTestClass -->
